org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.console=plain
systemProp.file.encoding=UTF-8
systemProp.sun.jnu.encoding=UTF-8
org.gradle.configuration-cache=false

loom_version=1.17.11
loader_version=0.19.3

mod_version=0.2.3
mod_group=net.billstark001
mod_id=worldmirror
archives_base_name=world-mirror

sqlite_version=3.47.1.0
